export default {
    en: {
        subscribe: 'Subscribe',
        design: 'Design',
        size: 'Size:',
        width: 'Width:',
        color: 'Color:',
        lineHeights: 'Interval:',
        background: 'Background:',
        border: 'Border:',
        margin: 'Margin',
        style: 'Style',
        requiredField: 'The field is required',
        field: {
            title: 'Fields',
            position: 'Position',
            header: 'Header',
            additionalField: 'Additional field variable in Selzy',
            type: 'Type',
            add: 'Add field',
            noTitle: '(No title)',
            fieldTitle: 'Field title',
            validate: 'Validation',
            edit: 'Edit',
            duplicate: 'Duplicate',
            delete: 'Delete',
            confirmDelete: 'Are you sure?',
            required: 'Required field',
            options: 'Options',
            dateFormat: 'Date format',
            emailRequired: 'Email is a required field to send a form to Selzy',
            settings: 'Go to additional fields settings in Selzy',
            key: 'Not set (will not be sent to Selzy)',
            uniquePhone: '<p style=\'white-space: nowrap\'>A field like \'Phone number\' already exists.</p> <p>You can add only one field of this type to this form.</p>',
            name: 'Name',
            phone: 'Phone number',
            text: 'Text',
            number: 'Number',
            select: 'Choose',
            boolean: 'Yes / No',
            date: 'Date',
            min: 'Min',
            max: 'Max',
            minLength: 'Minimum length',
            maxLength: 'Maximum length',
            regExp: 'regExp',
            cancel: 'Cancel',
        },
        offset: {
            outer: 'External',
            inner: 'Internal',
        },
        tooltip: {
            slug: '<p>Before you can use additional fields, you must create them on the Selzy platform. ' +
                'To do this, follow the link below this field.</p>' +
                '<p>After that, you will be able to link the additional Selzy field to the field on your site.</p>',
            dateFormat: '<p>Select date format.</p> <p><strong>dd</strong> - day.</p> <p><strong>mm</strong> - month.</p> <p><strong>yyyy</strong> - year.</p>',
            options: 'Specify options to select (each new line).',
        },
        message: {
            title: 'Messages',
            size: 'Size:',
            generalSettings: 'General settings',
            appearance: 'Appearance',
            formHeader: 'Form header',
            formDescription: 'Form description',
            successText: 'Thanks for subscribing',
            notification: 'Notifications',
            successSubscribe: 'You\'ve been successfully subscribed',
            validationError: 'Validation error',
            serverError: 'Server side error',
            minLength: 'Minimum length',
            maxLength: 'Maximum length',
            minNumber: 'Minimum number',
            maxNumber: 'Maximum number',
        },
        form: {
            title: 'Form',
            design: 'Form design',
            settings: 'Appearance',
        },
        button: {
            text: 'Button text'
        },
        errors: {
            validationErrorText: 'One or more fields contain an error. Please check and try again.',
            serverErrorText: 'An error occurred while sending the request. Please try again later.',
            minLengthErrorText: 'Field is too short.',
            maxLengthErrorText: 'Field is too long.',
            minNumberErrorText: 'The number is less than the minimum.',
            maxNumberErrorText: 'The number exceeds the maximum.',
            requiredErrorText: 'The field is required.',
            emailErrorText: 'Invalid email address.'
        }
    },
    ru: {
        subscribe: 'Подписаться',
        design: 'Оформление',
        size: 'Размер:',
        width: 'Толщина:',
        color: 'Цвет:',
        lineHeights: 'Интервал:',
        background: 'Фон:',
        border: 'Рамка:',
        margin: 'Отступы',
        style: 'Стиль',
        requiredField: 'Поле обязательно для заполнения',
        field: {
            title: 'Поля',
            position: 'Позиция',
            header: 'Заголовок',
            additionalField: 'Переменная дополнительного поля в Selzy',
            type: 'Тип',
            add: 'Добавить поле',
            noTitle: '(нет заголовка)',
            fieldTitle: 'Заголовок поля',
            validate: 'Валидация',
            edit: 'Редактировать',
            duplicate: 'Дублировать',
            delete: 'Удалить',
            confirmDelete: 'Вы уверены?',
            required: 'Обязательное поле',
            options: 'Варианты',
            dateFormat: 'Формат даты',
            emailRequired: 'Email является обязательным полем при отправке формы на платформу Selzy',
            settings: 'Перейти в настройки дополнительных полей Sezly',
            key: 'Не задано (не будет отправлено в Selzy)',
            uniquePhone: '<p style=\'white-space: nowrap\'>Поле типа \'Номер телефона\' уже существует.</p> <p>Вы можете добавить только одно поле данного типа в эту форму.</p>',
            name: 'Имя',
            phone: 'Номер телефона',
            text: 'Текст',
            number: 'Число',
            select: 'Выбор',
            boolean: 'Да / Нет',
            date: 'Дата',
            min: 'Минимум',
            max: 'Максимум',
            minLength: 'Минимальная длина',
            maxLength: 'Максимальная длина',
            regExp: 'Регулярное выражение',
            cancel: 'Отмена',
        },
        offset: {
            outer: 'Внешний',
            inner: 'Внутренний',
        },
        tooltip: {
            slug: '<p>Прежде чем использовать дополнительные поля, необходимо создать их на платформе Selzy. Чтобы это сделать, перейдите по ссылке под этим полем.</p> <p>После вы сможете привязать дополнительное поле Selzy к полю на Вашем сайте.</p>',
            dateFormat: '<p>Выберите нужный формат даты.</p> <p><strong>dd</strong> - день.</p> <p><strong>mm</strong> - месяц.</p> <p><strong>yyyy</strong> - год.</p>',
            options: 'Укажите варианты для выбора с новой строки каждый.',
        },
        message: {
            title: 'Сообщения',
            size: 'Размер:',
            generalSettings: 'Общие настройки',
            appearance: 'Настройка оформления',
            formHeader: 'Заголовок формы',
            formDescription: 'Описание формы',
            successText: 'Спасибо за подписку',
            notification: 'Уведомления',
            successSubscribe: 'Подписка прошла успешно',
            validationError: 'Ошибка валидации',
            serverError: 'Ошибка на стороне сервера',
            minLength: 'Минимальная длина',
            maxLength: 'Максимальная длина',
            minNumber: 'Минимальное число',
            maxNumber: 'Максимальное число',
        },
        form: {
            title: 'Форма',
            design: 'Оформление формы',
            settings: 'Настройка оформления',
        },
        button: {
            text: 'Текст кнопки'
        },
        errors: {
            validationErrorText: 'Одно или несколько полей содержат ошибку. Пожалуйста проверьте и попробуйте снова.',
            serverErrorText: 'При отправке запроса произошла ошибка. Пожалуйста, попробуйте позже.',
            minLengthErrorText: 'Поле слишком короткое.',
            maxLengthErrorText: 'Поле слишком длинное.',
            minNumberErrorText: 'Число меньше допустимого минимума.',
            maxNumberErrorText: 'Число превышает максимально допустимое.',
            requiredErrorText: 'Поле обязательно для заполнения.',
            emailErrorText: 'Введенный адрес электронной почты недействителен.'
        }
    },
    pt: {
        subscribe: 'Se inscrever',
        design: 'Decoração',
        size: 'O tamanho:',
        width: 'Espessura:',
        color: 'Cor:',
        lineHeights: 'Intervalo:',
        background: 'Fundo:',
        border: 'Quadro:',
        margin: 'Recuo',
        style: 'Estilo',
        requiredField: 'Campo obrigatório',
        field: {
            title: 'Campos',
            position: 'Posição',
            header: 'Cabeçalho',
            additionalField: 'Variável de campo adicional em Selzy',
            type: 'Tipo',
            add: 'Adicionar campo',
            noTitle: '(não há título)',
            fieldTitle: 'Título do campo',
            validate: 'Validação',
            edit: 'Editar',
            duplicate: 'Duplicado',
            delete: 'Retirar',
            confirmDelete: 'tem certeza?',
            required: 'Campo obrigatório',
            options: 'Opções',
            dateFormat: 'Formato de data',
            emailRequired: 'E-mail é um campo obrigatório ao enviar um formulário para a plataforma Selzy',
            settings: 'Vá para as configurações de campo avançadas do Selzy',
            key: 'Não especificado (não será enviado para Selzy)',
            uniquePhone: '<p style=\'white-space: nowrap\'>Já existe um campo do tipo \'Número de telefone\'.</p> <p>Você pode adicionar apenas um campo de um determinado tipo a este formulário.</p>',
            name: 'Nome',
            phone: 'Número de telefone',
            text: 'Texto',
            number: 'Número',
            select: 'Escolha',
            boolean: 'Bem não',
            date: 'Data de',
            min: 'Mínimo',
            max: 'Máximo',
            minLength: 'Comprimento mínimo',
            maxLength: 'Comprimento máximo',
            regExp: 'Expressão regular',
            cancel: 'Cancelar',
        },
        offset: {
            outer: 'Externo',
            inner: 'Interior',
        },
        tooltip: {
            slug: '<p>Antes de poder usar campos adicionais, você deve criá-los na plataforma Selzy.\n' +
                'Para fazer isso, siga o link abaixo deste campo.</p> <p>Depois disso, você poderá vincular o campo Selzy adicional ao campo em seu site.</p>',
            dateFormat: '<p>Selecione o formato de data desejado.</p> <p><strong>dd</strong> - Dia.</p> <p><strong>mm</strong> - Mês.</p> <p><strong>yyyy</strong> - Ano.</p>',
            options: 'Especifique opções para selecionar em uma nova linha cada.',
        },
        message: {
            title: 'Mensagens',
            size: 'O tamanho:',
            generalSettings: 'Configurações Gerais',
            appearance: 'Personalização de aparência',
            formHeader: 'Cabeçalho do formulário',
            formDescription: 'Descrição do formulário',
            successText: 'Grato pela assinatura',
            notification: 'Notificações',
            successSubscribe: 'Assinatura bem-sucedida',
            validationError: 'Erro de validação',
            serverError: 'Erro do lado do servidor',
            minLength: 'Comprimento mínimo',
            maxLength: 'Comprimento máximo',
            minNumber: 'Número mínimo',
            maxNumber: 'Numero maximo',
        },
        form: {
            title: 'A forma',
            design: 'Design de formulário',
            settings: 'Personalização de aparência',
        },
        button: {
            text: 'Botão de texto'
        },
        errors: {
            validationErrorText: 'Um ou mais campos contêm um erro. Por favor verifique e tente novamente.',
            serverErrorText: 'Ocorreu um erro ao enviar a solicitação. Por favor, tente novamente mais tarde.',
            minLengthErrorText: 'Campo muito curto.',
            maxLengthErrorText: 'Campo muito longo.',
            minNumberErrorText: 'O número é menor que o mínimo permitido.',
            maxNumberErrorText: 'O número excede o máximo permitido.',
            requiredErrorText: 'Campo obrigatório.',
            emailErrorText: 'O endereço de e-mail inserido é inválido.'
        }
    },
    uk: {
        subscribe: 'Підписатися',
        design: 'Оформлення',
        size: 'Розмір:',
        width: 'Товщина:',
        color: 'Колір:',
        lineHeights: 'Інтервал:',
        background: 'Фон:',
        border: 'Рамка:',
        margin: 'Відступ',
        style: 'Стиль',
        requiredField: 'Поле обов\'язкове для заповнення',
        field: {
            title: 'Поля',
            position: 'Позиція',
            header: 'Заголовок',
            additionalField: 'Змінна додаткова поля у Selzy',
            type: 'Тип',
            add: 'Додати поле',
            noTitle: '(Немає заголовку)',
            fieldTitle: 'Заголовок поля',
            validate: 'Валідація',
            edit: 'Редагувати',
            duplicate: 'Дублювати',
            delete: 'Видалити',
            confirmDelete: 'Ви впевненні?',
            required: 'Обов\'язкове поле',
            options: 'Варіанти',
            dateFormat: 'Формат дати',
            emailRequired: 'Email є обов\'язковим полем при надсиланні форми на платформу Selzy',
            settings: 'Перейти до налаштування додаткових полів Selzy',
            key: 'Не задано (не буде відправлено до Selzy)',
            uniquePhone: '<p style=\'white-space: nowrap\'>Поле типу \'Номер телефону\' вже існує.</p> <p>Ви можете додати лише одне поле даного типу у цю форму.</p>',
            name: 'Ім\'я',
            phone: 'Номер телефона',
            text: 'Текст',
            number: 'Число',
            select: 'Вибір',
            boolean: 'Так / Ні',
            date: 'Дата',
            min: 'Мінімум',
            max: 'Максимум',
            minLength: 'Мінімальна довжина',
            maxLength: 'Максимальна довжина',
            regExp: 'Регулярний вираз',
            cancel: 'Скасувати',
        },
        offset: {
            outer: 'Зовнішній',
            inner: 'Внутрішній',
        },
        tooltip: {
            slug: '<p>Перш ніж використовувати додаткові поля, потрібно створити їх на платформі Selzy.\n' +
                'Щоб це зробити, перейдіть за посиланням під цим полем.</p> <p>Після цього ви зможете прив\'язати додаткове поле Selzy до поля на Вашому сайті.</p>',
            dateFormat: '<p>Виберіть потрібний формат дати.</p> <p><strong>dd</strong> - День.</p> <p><strong>mm</strong> - Місяць.</p> <p><strong>yyyy</strong> - Рік.</p>',
            options: 'Вкажіть варіанти для вибору (кожен з нового рядка).',
        },
        message: {
            title: 'Повідомлення',
            size: 'Розмір:',
            generalSettings: 'Загальні налаштування',
            appearance: 'Налаштування оформлення',
            formHeader: 'Заголовок форми',
            formDescription: 'Опис форми',
            successText: 'Дякую за підписку',
            notification: 'Повідомлення',
            successSubscribe: 'Підписка пройшла успішно',
            validationError: 'Помилка валідації',
            serverError: 'Помилка на стороні сервера',
            minLength: 'Мінімальна довжина',
            maxLength: 'Максимальна довжина',
            minNumber: 'Мінімальне число',
            maxNumber: 'Максимальна кількість',
        },
        form: {
            title: 'Форма',
            design: 'Оформлення форми',
            settings: 'Налаштування оформлення',
        },
        button: {
            text: 'Текст кнопки'
        },
        errors: {
            validationErrorText: 'Одне чи кілька полів містять помилку. Будь ласка перевірте та спробуйте знову.',
            serverErrorText: 'При надсиланні запиту виникла помилка. Будь ласка, спробуйте пізніше.',
            minLengthErrorText: 'Поле надто коротке.',
            maxLengthErrorText: 'Поле надто довге.',
            minNumberErrorText: 'Число менше допустимого мінімуму.',
            maxNumberErrorText: 'Число перевищує максимально допустиме.',
            requiredErrorText: 'Поле обов\'язкове для заповнення.',
            emailErrorText: 'Введена адреса електронної пошти недійсна.'
        }
    }
}